name: deploy backend

on:
  push:
    branches: [main]
    paths:
      - 'packages/server/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build

  deploy:
    needs: build
    name: Deploy backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: '.'
          target: '/home/ubuntu/github-action'
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/github-action
            rm -rf packages/web
            yarn install
            cd packages/server
            yarn build
